---
- name: Configuracion servidor base de datos en Ubuntu
  hosts: server02
  become: true
  user: sysadmin

  tasks:
  
## Configuracion Firewall y trafico

  - name: UFW instalado
    ansible.builtin.apt:
      name: ufw
      state: present

  - name: Permitir puerto 22 en ufw
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Defino politicas de tráfico entrante
    community.general.ufw:
      policy: allow
      direction: outgoing
      state: enabled

  - name: Defino politicas de tráfico entrante
    community.general.ufw:
      policy: deny
      direction: incoming
      state: enabled

  - name: servicio UFW levantado y activo
    ansible.builtin.systemd_service:
      name: ufw
      state: started
      enabled: true
      
## Instalación de MariaDB
  
  - name: MariaDB instalado
    ansible.builtin.apt:
      name: mariadb-server
      state: present
      update-cache: true
    loop:
      - mariadb-server
      - mariadb-client
      - python3-pymysql

  - name: Cambiar la configuracion para escuchar en todas las interfaces
    ansible.builtin.lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address'
      line: 'bind-address         = 0.0.0.0'
    notify: Restart mariadb

  - name: Ejecuto el handler si cambió la configuración
    meta: flush_handlers

  - name: Servidor Mariadb levantado
    ansible.builtin.systemd_service: 
      name: mariadb
      state: started
      enabled: true

  - name: Habilitamos en ufw la conexión a mariadb
    community.general.ufw:
      rule: allow
      port: '3306'
      protocol: tcp
      direction: in

##  Configuracion de la base de datos de la aplicación

  - name: Copio el dump de la base de datos
    ansible.builtin.copy:
      src: ./files/todo.sql
      dest: /tmp/todo.sql

  - name: Creacion base de datos Todo
    community.mysql.mysql_db:
      check_implicit_admin: true
      login_host: localhost
      login_user: root
      login_password: dbadmin
      name: todo
      state: import
      target: ./files/todo.sql
      
## Remover base de datos de prueba

  - name: Remove test database and access
    mysql_db:
      name: test
      state: absent
      
  handlers:

  - name: Reiniciar mariadb
    ansible.builtin.systemd_service: 
      name: mariadb
      state: restarted
