---
- name: Instalar todo en Centos
  hosts: centos
  user: sysadmin
  become: true
  
  tasks:
  
  - name: Instalar tar
    ansible.builtin.dnf:
      name: tar
      state: present
        
  - name: Descargar Tomcat
    ansible.builtin.get_url:
      url: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz."
      dest: "/tmp/apache-tomcat-9.0.56.tar.gz"
      mode: '0644'

  - name: Extraer Tomcat
    ansible.builtin.unarchive:
      src: "/tmp/apache-tomcat-9.0.56.tar.gz"
      dest: "/opt"
      remote_src: true

  - name: Seteo variable con ruta donde está el tomcat
    ansible.builtin.set_fact:
      dir_tomcat: "{{ tomcat_file.path | splitext | first | splitext | first }}"

  - name: Creo enlace a tomcat
    ansible.builtin.file:
      src: "/opt/tomcat"
      dest: /opt/tomcat
      state: link
      force: true
        
## Los puertos de 8080 se abrieron en el webserver.yml

  - name: Iniciar Tomcat
    ansible.builtin.systemd_service:
      name: tomcat
      state: started
      enabled: true

  - name: Copiar Todo.war al directorio de Tomcat
    ansible.builtin.copy:
      src: /Tallerjulio2024/files/todo.war
      dest: /opt/tomcat/webapps/todo.war

  - name: Reiniciar Tomcat
    ansible.builtin.systemd_service:
      name: tomcat
      state: restarted
