---
- name: Instalacion y configuracion webserver
  hosts: centos
  become: true
  user: sysadmin

  tasks:

  - name: Instalar httpd (Apache)
    ansible.builtin.dnf:
      name: httpd
      state: present

  - name: Levantar y habilitar servicio httpd
    ansible.builtin.systemd_service:
      name: httpd
      enabled: true
      state: started

  - name: Crear directorio document root
    ansible.builtin.file:
      path: /var/www/html/obligatorio
      state: directory
      owner: apache
      group: apache
      mode: '0755'

  - name: Copiar pagina index.j2
    ansible.builtin.copy:
      src: ./templates/index.j2
      dest: /var/www/html/obligatorio/index.html
      owner: apache
      group: apache
      mode: '0644'
      
  - name: Configurar virtualhost 80
    ansible.builtin.template: 
      src: ./files/virtualhost.conf
      dest: /etc/httpd/conf.d
      owner: apache
      group: apache
      mode: '0644'
  
  - name: Abrir puertos 80 en firewall
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
    notify: Reinicio firewalld
    
  - name: Abrir puerto 8080 en firewall
    ansible.posix.firewalld:
      port: 8080/tcp
      permanent: true
      state: enabled
    notift: Reinicio firewalld
       
  handlers:
  
- name: Reinicio Firewalld:
     ansible.builtin.systemd:
       name: firewalld
       state: reload
  
  - name: Reiniciar apache
    ansible.builtin.systemd_service:
      name: httpd
      state: restarted

